#!/data/data/com.termux/files/usr/bin/bash

# Termux:X11 açma
kill -9 $(pgrep -f "termux.x11") 2>/dev/null

# Ses
pulseaudio --start --load="module-native-protocol-tcp auth-ip-acl=127.0.0.1 auth-anonymous=1" --exit-idle-time=-1

# Termux:X11 oturumu hazırlama
export XDG_RUNTIME_DIR=${TMPDIR}
termux-x11 :0 >/dev/null &

# Bekle
sleep 3

# Aç Termux:X11
am start --user 0 -n com.termux.x11/com.termux.x11.MainActivity > /dev/null 2>&1
sleep 1

# Parduw XFCE aç
proot-distro login pardus --shared-tmp -- /bin/bash -c  'export PULSE_SERVER=127.0.0.1 && export XDG_RUNTIME_DIR=${TMPDIR} && su - kullanıcı -c "LANG=tr_TR.UTF-8 && env DISPLAY=:0 startxfce4"'

exit 0
